# Setup
title:               Aadhityans Website
tagline:             'Bored at home 8 year old student'
description:         'Bored at home 8 year old student'
url:                 http://goodatwritingstory.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Aadthiyan
  url:               https://twitter.com/goodatwrtings1
  email:             goodatwritingstory@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-4921442-2
